name: Context variables demo
on:
  workflow_dispatch:
env:
  common: "Some Data"
jobs:
  DemonstrateEnvVars:
    runs-on: ubuntu-latest
    steps:
      - name: below code access env vars defined for all jobs
        run: echo "Value of common env var is - ${{ env.common }}"
  OtherJob:
    runs-on: ubuntu-latest
    steps:
      - name: trying to access env var from prev job
        run: echo "Common env var - ${{ env.common }}"
