name: GitHub Workflow Demo
on: push
jobs:
  Example-action-job:
    name: Exploring demo job
    runs-on: ubuntu-latest
    steps:
      #Display the event that triggered the workflow run
      - run: echo "This job is triggred on {{ github.event_name }} event"

      #Runner information
      - run: echo "This job is running on {{ runner.os }} OS."
      
