name: Data dharing using Job output
on:
  workflow_dispatch:
jobs:
  JOB1:
    runs-on: ubuntu-latest
    outputs:
      message: "Message from job 1"
      url: ${{ steps.step1.outputs.url }}
    steps:
      - uses: actions/checkout@v2
      - id: step1
        name: assigns url
        run: echo "::set-output name=url::https://ps.com"
  JOB2:
    runs-on: ubuntu-latest
    needs: JOB1
    steps:
      - name: Print message from JOB1
        run: echo ${{ needs.JOB1.outputs.message }}
      - name: Print url from JOB1
        run: echo ${{ needs.JOB1.outputs.url }} 
