name: Data Sharing using Upload-Download Artifacts
on:
  workflow_dispatch:
jobs:
  UploadJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
      - uses: actions/upload-artifact@v3
        with:
          name: Node Build
          path: dist
  DownloadJob:
    runs-on: ubuntu-latest
    needs: UploadJob
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Build
          path: build
      - run: zip -r build.zip build/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build.zip"
