name: Manual Trigger of Workflow file
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Some name"
        required: true
        default: "John"
      deploy:
        description: "Deploy data"
        required: true
        default: "some data"
jobs:
  Demo:
    name: access input values
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: echo "name - ${{ github.event.inputs.name }}"
    
